[package]
name = "the-bullpen-game"
version = "0.0.1"
edition = "2021"

[dependencies]
avian3d = "^0.1.2"
bevy = { version = "^0.14.0", features = ["dynamic_linking"] }
# glam = { version = "^0.27.0", features = ["glam-assert"] }
bevy_flycam = "^0.14.1"
blenvy = { git = "https://github.com/kaosat-dev/Blenvy/", branch = "blenvy", version = "^0.1.0-alpha.1" }
leafwing-input-manager = "^0.14.0"
log = "^0.4.22"
bevy-inspector-egui = "^0.25.1"
bevy_third_person_camera = "0.1.11"
bevy-avian-baseball-flight = "0.0.1-alpha.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
