[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.x86_64-apple-darwin]
rustflags = []

[target.aarch64-apple-darwin]
rustflags = []

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = ["-Zshare-generics=n", "-Zthreads=0"]

[alias]
ci = "run --package ci --"
